version: '3'

services:

  app:
    container_name: node-app
    build:
      context: node
    entrypoint: dockerize --wait tcp://db:3306 --timeout 20s docker-entrypoint.sh node index.js
    volumes:
      - ./node:/usr/src/app
    networks:
      - desafio-node-nginx
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db-node
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-node-nginx

networks:
  desafio-node-nginx:
    driver: bridge
